V1.0.0 Release PR
eastgenomics/eggd_ici_uploader pull request #4
Opened 2024-11-13 16:38 UTC by spaul91

This PR contains the commit intended to be packaged as the release of V1.0.0 of `eggd_ici_uploader`

2024-11-14 11:10 UTC, RSWilson1 requested changes
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4)* status: 1 of 8 files reviewed, 13 unresolved discussions (waiting on @spaul91)

___
*[`Dockerfile` line 17 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOZs3-3g-Zeq8I6eQ:-OBaOZs3-3g-Zeq8I6eR:b-hte5ek) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/Dockerfile#L17)):*
> ```Dockerfile
>     # We're using "|| exit 0" to stop the exit code from breaking docker build.
>     (./ici-uploader install || exit 0) && \
>     rm ./*
> ```

what are you trying to remove here? Could it be more explicit?
___
*[`README.md` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPgC87eB9LLeMlGBY:-OBaPgC87eB9LLeMlGBZ:b-dtsh6e) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L32)):*
> ```Markdown
> dx run app-eggd_ici_uploader/1.0.0 \
>   -irun_folder="<run project ID>:</path/to/output/folder>" \
>   -iworkflow_id="<workflow ID string>" \
> ```

Can you add something here how we find the workflow id and what this does?
___
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBaQ_i0BXJPqr4iqeNw:bj4p4hy) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
> ```Markdown
>   -iapi_key="<API key file>"
> ```
> ```

could you give an example of the run cmd with a fake project id.
___
*[`src/script.sh` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQFQS1Z2NLXd6GKkU:-OBaQFQS1Z2NLXd6GKkV:bqtemvl) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L6)):*
> ```Shell
> # To report errors specifically:
> #   dx-jobutil-report-error "My error message"
> ```

could you add some comments explaining the positional variables.
i.e.  $1 ==  Run path to the run folder in DNAnexus i.e. example_path/
___
*[`src/script.sh` line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBeBz1o8N8pQb7GE5P1:-OBeBz1o8N8pQb7GE5P2:b-84mlpw) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L11)):*
> ```Shell
>     OUT_FOLDER=$(sed "s:/$::g" <<< $2) # removes trailing "/" if present
> 
>     if grep -Eq "^project-" <<< $RUN_PATH; then
> ```

Would be good to quote any path variables i.e. "${SAMPLESHEET_PATH}" or "${RUN_PATH}" see google style guide: https://google.github.io/styleguide/shellguide.html#quoting
___
*[`src/script.sh` line 45 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe5G5a3SN-mPmONutn:-OBe5G5a3SN-mPmONuto:bmzl0ie) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L45)):*
> ```Shell
>     echo "Sample_ID,Case_ID,Tumor_Type" > custom_case_metadata.csv
> 
>     # the numeric string is the SNOMED ID for "Tumor of Unknown Origin"
> ```

Might be useful to be explicit here i.e. "255051004" is the SNOMED CT ID..
___
*[`src/script.sh` line 47 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaRxij6oiklLRzbwrB:-OBaRxij6oiklLRzbwrC:bubnjo4) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L47)):*
> ```Shell
>     # the numeric string is the SNOMED ID for "Tumor of Unknown Origin"
>     for SAMPLE in ${SAMPLE_ARRAY[@]}; do
>         echo "${SAMPLE},${SAMPLE},255051004" >> custom_case_metadata.csv
> ```

255051004 this is the id for tumour of unknown origin write? Could we have this configurable as an input in-case we want to change the snomed id?
___
*[`src/script.sh` line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe28n9BnmhfHkJ-b5q:-OBe28nA4HIyQ1mapkCB:b-qi7qh7) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L70)):*
> ```Shell
>     # head -n1 returns the first match in the first directory where a samplesheet is found
>     ## Potential issue: what happens if there's more than one samplesheet in the topmost directory?
>     SAMPLESHEET_PATH=$(find in/ -iname "*SampleSheet*.csv" | head -n1)
> ```

I think it would be good to add some handling for multiple samplesheets here, as we don't want to be using a samplesheet if multiple exist in the top most directory.
___
*[`src/script.sh` line 89 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe3zsE4NkGdO2hhS-f:-OBe3zsE4NkGdO2hhS-g:bqo92vq) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L89)):*
> ```Shell
>         -itd $DOCKER_IMAGE
> 
>     if [ $dry_run == true ]; then
> ```

This is a nice feature!
___
*[`Readme.md` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPuLj02woTqCz4KpU:-OBaPuLj02woTqCz4KpV:b-re62pf) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/Readme.md#L1)):*
> ```Markdown
> <!-- dx-header -->
> ```

should this readme exist? Looks like it was accidentally committed?
___
*[`ici-uploader-image/dxasset.json` line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ5APBeEbn8m_DDXa:-OBaQ5APBeEbn8m_DDXb:b-hv3okv) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/ici-uploader-image/dxasset.json#L7)):*
> ```JSON
>   "version": "1.0.0",
>   "distribution": "Ubuntu",
>   "instanceType": "mem2_ssd1_x4",
> ```

is this instance type correct, it differs from the dxapp.json, is that because this is an asset?
___
*[`Readme.developer.md` line 3 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ-tH-dex7zllx7Ps:-OBaQ-tH-dex7zllx7Pt:bzhsg2i) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/Readme.developer.md#L3)):*
> ```Markdown
> # eggd_ici_uploader Developer Readme
> 
> <!--
> ```

same for this, is it meant to be here? if so could you add some documentation?
___
*[`dxapp.json` line 12 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOdUZ8MH4DEQKj572:-OBaOdUZ8MH4DEQKj573:b-y1rm73) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/dxapp.json#L12)):*
> ```JSON
>   },
>   "developers": [
>       "user-spaul4",
> ```

can you remove your user name from this as our standards are to just have "org-emee_1"
___
*[`dxapp.json` line 57 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOtrGEitwiD_wFM6W:-OBaOtrGEitwiD_wFM6X:bdpcgkf) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/dxapp.json#L57)):*
> ```JSON
>       "timeoutPolicy": {
>           "*": {
>               "hours": 48
> ```

Is this a reasonable timeout period? We expect it to take 2 hours?


<!-- Sent from Reviewable.io -->

2024-11-14 12:30 UTC, spaul91 commented
*[`README.md` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPgC87eB9LLeMlGBY:-OBedjea4_rHPcdvffW5:bm3qhis) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L32)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Can you add something here how we find the workflow id and what this does?
</blockquote></details>

See "# What data are required for this app to run?" for the definition


<!-- Sent from Reviewable.io -->

2024-11-14 12:31 UTC, spaul91 commented
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBedqp22OIqVpHA-PjO:b-t55fhn) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

could you give an example of the run cmd with a fake project id.
</blockquote></details>

Why specifically the project ID?


<!-- Sent from Reviewable.io -->

2024-11-14 12:35 UTC, spaul91 commented
*[`ici-uploader-image/dxasset.json` line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ5APBeEbn8m_DDXa:-OBeezdk1esfT42AiZk_:b8crc2p) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/ici-uploader-image/dxasset.json#L7)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

is this instance type correct, it differs from the dxapp.json, is that because this is an asset?
</blockquote></details>

This is the instance used to build the asset, not run it. It's invoked once


<!-- Sent from Reviewable.io -->

2024-11-14 12:46 UTC, spaul91 commented
*[`Dockerfile` line 17 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOZs3-3g-Zeq8I6eQ:-OBehL14EAYkvECVvGCz:b-m7hogh) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/Dockerfile#L17)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

what are you trying to remove here? Could it be more explicit?
</blockquote></details>

Intermediate install files. I've added a comment


<!-- Sent from Reviewable.io -->

2024-11-14 12:58 UTC, spaul91 commented
*[`src/script.sh` line 47 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaRxij6oiklLRzbwrB:-OBeigF85SLFgPs0FIDu:bl6acot) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L47)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

255051004 this is the id for tumour of unknown origin write? Could we have this configurable as an input in-case we want to change the snomed id?
</blockquote></details>

Would we ever want to change the SNOMED ID? This is essentially a hack to kick-start processing. If we make this configurable, we'll want to add a way to pass in new SNOMED IDs, and I can't think of a scenario where we'd want to apply the same ID to every sample unless it's just to get processing to begin. I doubt we'll want to swap "Tumour of Unknown Origin" to "Unknown Tumour", for example.

On the other hand, if we get to a point where we want to apply SNOMED IDs that are specific to each sample's tumour types, we'll need to completely rewrite this function (and likely other parts of the program) since the script's goal here will change.


<!-- Sent from Reviewable.io -->

2024-11-14 13:01 UTC, spaul91 commented
*[`src/script.sh` line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe28n9BnmhfHkJ-b5q:-OBekIf780nPjvcc1zUF:brntb8m) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L70)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

I think it would be good to add some handling for multiple samplesheets here, as we don't want to be using a samplesheet if multiple exist in the top most directory.
</blockquote></details>

I think this is something we should discuss as a group, since this has implications for the workflow config too


<!-- Sent from Reviewable.io -->

2024-11-14 13:02 UTC, spaul91 commented
*[`src/script.sh` line 89 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe3zsE4NkGdO2hhS-f:-OBektQtAyhcnmjm0Rgo:b-vegfaj) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L89)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

This is a nice feature!
</blockquote></details>

Thanks :) it's a nice feature I forgot to give the user an opportunity to invoke because there's no user argument for it haha. If I add it I'll need to repeat all the testing... will decide if it's something I want to do


<!-- Sent from Reviewable.io -->

2024-11-14 13:03 UTC, spaul91 commented
*[`Dockerfile` line 17 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOZs3-3g-Zeq8I6eQ:-OBelGwm1KqYmCVX7BBE:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/Dockerfile#L17)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Intermediate install files. I've added a comment
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-14 13:03 UTC, spaul91 commented
*[`dxapp.json` line 12 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOdUZ8MH4DEQKj572:-OBelKXh3zrHScTwu6oV:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/dxapp.json#L12)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

can you remove your user name from this as our standards are to just have "org-emee_1"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-14 13:03 UTC, spaul91 commented
*[`dxapp.json` line 57 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOtrGEitwiD_wFM6W:-OBelM7QEJzU9XdC8EUO:b-h5hhcs) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/dxapp.json#L57)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Is this a reasonable timeout period? We expect it to take 2 hours?
</blockquote></details>

Reduced to 3 hours, to give us an extra hour of leeway just in case


<!-- Sent from Reviewable.io -->

2024-11-14 13:03 UTC, spaul91 commented
*[`dxapp.json` line 57 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOtrGEitwiD_wFM6W:-OBelRVHCuZmz8afDTIO:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/dxapp.json#L57)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Reduced to 3 hours, to give us an extra hour of leeway just in case
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-14 13:11 UTC, spaul91 commented
*[`src/script.sh` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQFQS1Z2NLXd6GKkU:-OBem7kY1r29wpK4QG77:b1dwsrk) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L6)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

could you add some comments explaining the positional variables.
i.e.  $1 ==  Run path to the run folder in DNAnexus i.e. example_path/
</blockquote></details>

I'm not so sure that this is non-obvious, and the google style guide recommends you don't add comments to functions that are short and obvious. That said, I didn't read the style guide before writing this script, so I should probably review the rest of the code and make sure it's compliant.

Is it the google style guide the one our group follows for bash scripts?


<!-- Sent from Reviewable.io -->

2024-11-14 13:21 UTC, spaul91 commented
*[`src/script.sh` line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBeBz1o8N8pQb7GE5P1:-OBepRTd2HAMz_F31l_i:b-cuy5i6) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L11)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Would be good to quote any path variables i.e. "${SAMPLESHEET_PATH}" or "${RUN_PATH}" see google style guide: https://google.github.io/styleguide/shellguide.html#quoting
</blockquote></details>

Agreed, will go back and add them


<!-- Sent from Reviewable.io -->

2024-11-14 13:21 UTC, spaul91 commented
*[`Readme.md` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPuLj02woTqCz4KpU:-OBepVmJ5qAoR7FodeEF:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/Readme.md#L1)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

should this readme exist? Looks like it was accidentally committed?
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2024-11-14 13:21 UTC, spaul91 commented
*[`Readme.developer.md` line 3 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ-tH-dex7zllx7Ps:-OBep_1mECFCAWH6ldvZ:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/Readme.developer.md#L3)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

same for this, is it meant to be here? if so could you add some documentation?
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2024-11-14 13:53 UTC, RSWilson1 requested changes
> Reviewed 1 of 8 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @spaul91)

___
*[`dxapp.json` line 57 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOtrGEitwiD_wFM6W:-OBewTDN-bhtJq9PiU4v:bps43wa) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/dxapp.json#L57)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Sorry to ask again but I think we should be a bit more liberal with the time out so maybe 4 hours?
___
*[`README.md` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPgC87eB9LLeMlGBY:-OBeqU6FA8MKKiT-XHKP:b-w6w4q8) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L32)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

See "# What data are required for this app to run?" for the definition
</blockquote></details>

Maybe just adding some info to the # What data are required for this app to run?" on what this configures?
___
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBeqgJuDa9Y-INUM16n:bfd2ivc) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Why specifically the project ID?
</blockquote></details>

I just meant an example cmd with fake data.
i.e 
```bash
dx run app-eggd_ici_uploader/1.0.0 \
  -irun_folder="project-1234:tso500/output/" \
  -iworkflow_id="1234-1234-1234" \
  -iapi_key="<API key file>"
```
Specifically showing the path we use for TSO500 currently so if anyone picked this up they would have a better idea how this works.
___
*[`ici-uploader-image/dxasset.json` line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ5APBeEbn8m_DDXa:-OBeozQy7k9HPyWcSJ3h:btojbfd) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/ici-uploader-image/dxasset.json#L7)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

This is the instance used to build the asset, not run it. It's invoked once
</blockquote></details>

Great!
___
*[`src/script.sh` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQFQS1Z2NLXd6GKkU:-OBeoYCq3UBsfFZSi3uJ:bddgl4q) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L6)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I'm not so sure that this is non-obvious, and the google style guide recommends you don't add comments to functions that are short and obvious. That said, I didn't read the style guide before writing this script, so I should probably review the rest of the code and make sure it's compliant.

Is it the google style guide the one our group follows for bash scripts?
</blockquote></details>

Yeah that's fair enough, I think it's quite clear for this one. I was quoting the style guide just for the best practice of quoting really, not sure if we have finalised a style guide for shell scripts ShellCheck is mentioned in the draft development guide so maybe follow that.
___
*[`src/script.sh` line 47 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaRxij6oiklLRzbwrB:-OBerBej2qK_p4qdY7dD:b-qiuvag) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L47)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Would we ever want to change the SNOMED ID? This is essentially a hack to kick-start processing. If we make this configurable, we'll want to add a way to pass in new SNOMED IDs, and I can't think of a scenario where we'd want to apply the same ID to every sample unless it's just to get processing to begin. I doubt we'll want to swap "Tumour of Unknown Origin" to "Unknown Tumour", for example.

On the other hand, if we get to a point where we want to apply SNOMED IDs that are specific to each sample's tumour types, we'll need to completely rewrite this function (and likely other parts of the program) since the script's goal here will change.
</blockquote></details>

my thought would be if we then apply this to MYE as well as TSO500 there might be a use-case for running this with a different snomed CT ID. I agree would require a re-write if we want to add individual snomed ct ids.


<!-- Sent from Reviewable.io -->

2024-11-14 16:09 UTC, spaul91 commented
*[`dxapp.json` line 57 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaOtrGEitwiD_wFM6W:-OBfR-tk8PFOteG8BaJF:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/dxapp.json#L57)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Sorry to ask again but I think we should be a bit more liberal with the time out so maybe 4 hours?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-14 16:13 UTC, spaul91 commented
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBfR2n8184Hvhi3DWNL:b1tmmvi) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

I just meant an example cmd with fake data.
i.e 
```bash
dx run app-eggd_ici_uploader/1.0.0 \
  -irun_folder="project-1234:tso500/output/" \
  -iworkflow_id="1234-1234-1234" \
  -iapi_key="<API key file>"
```
Specifically showing the path we use for TSO500 currently so if anyone picked this up they would have a better idea how this works.
</blockquote></details>

I'm sorry, but I respectfully disagree. It's a feature of DNANexus, and anyone using this app should be familiar with the way paths are specified. I think it's fine as it is, and I don't see what's ambiguous about the placeholders I'm using already


<!-- Sent from Reviewable.io -->

2024-11-14 16:20 UTC, spaul91 commented
*[`README.md` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPgC87eB9LLeMlGBY:-OBfS1aD1VMyTvRI3lAv:b-1rnoex) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L32)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Maybe just adding some info to the # What data are required for this app to run?" on what this configures?
</blockquote></details>

Isn't it enough as it is? The section tells you to get the workflow ID from ICI, and I don't think it should be the responsibility of these docs to outline all of the steps needed to define and copy a workflow ID from ICI.

I'm afraid I don't quite understand what you need from me on this, so if you know what to replace this with, please feel free to make the edits and open a PR against the dev branch.


<!-- Sent from Reviewable.io -->

2024-11-14 16:22 UTC, spaul91 commented
*[`src/script.sh` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQFQS1Z2NLXd6GKkU:-OBfTkMP8RENrn70i8K5:brisyn9) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L6)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Yeah that's fair enough, I think it's quite clear for this one. I was quoting the style guide just for the best practice of quoting really, not sure if we have finalised a style guide for shell scripts ShellCheck is mentioned in the draft development guide so maybe follow that.
</blockquote></details>

I've updated the script to follow SpellCheck conventions. I've left out the function comments because I don't think they're complex enough to warrant the verbiage


<!-- Sent from Reviewable.io -->

2024-11-14 16:22 UTC, spaul91 commented
*[`src/script.sh` line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBeBz1o8N8pQb7GE5P1:-OBfTzT5EWCScG9MxRQC:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L11)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Agreed, will go back and add them
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-14 16:26 UTC, spaul91 commented
*[`src/script.sh` line 47 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaRxij6oiklLRzbwrB:-OBfUUXe5z9ZxMJbw7Hu:b-bdyis5) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L47)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

my thought would be if we then apply this to MYE as well as TSO500 there might be a use-case for running this with a different snomed CT ID. I agree would require a re-write if we want to add individual snomed ct ids.
</blockquote></details>

I don't think so, SNOMED IDs should be specific to samples, but the way we're using them right now is just as a placeholder until something specific is decided on. This won't change across pipelines for the time being.


<!-- Sent from Reviewable.io -->

2024-11-15 12:01 UTC, spaul91 commented
*[`src/script.sh` line 45 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe5G5a3SN-mPmONutn:-OBjglVv-_k7PtUclBjV:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L45)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Might be useful to be explicit here i.e. "255051004" is the SNOMED CT ID..
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-15 12:08 UTC, RSWilson1 requested changes
> Reviewed 1 of 8 files at r1, 1 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> Dismissed @RSWilson1 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4)* status: all files reviewed, 4 unresolved discussions (waiting on @spaul91)

___
*[`README.md` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPgC87eB9LLeMlGBY:-OBjhdiO7n01XT7FBWVS:b-rspr71) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L32)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Isn't it enough as it is? The section tells you to get the workflow ID from ICI, and I don't think it should be the responsibility of these docs to outline all of the steps needed to define and copy a workflow ID from ICI.

I'm afraid I don't quite understand what you need from me on this, so if you know what to replace this with, please feel free to make the edits and open a PR against the dev branch.
</blockquote></details>

* An ICI workflow ID specific to the workflow targeting your pipeline output.
This is defined within ICI specifying: genome reference, filters used, report template, variant flags and automation setting.
___
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBjhVCx4XEwsgg84KhC:b-jrj8gv) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I'm sorry, but I respectfully disagree. It's a feature of DNANexus, and anyone using this app should be familiar with the way paths are specified. I think it's fine as it is, and I don't see what's ambiguous about the placeholders I'm using already
</blockquote></details>

I would like to see the path like "<FULL PATH TO FOLDER>/eggd_tso500/" recorded somewhere which is the example you shared in the slack channel, just so it is clear for anyone else picking this up which folder to point to and not get the wrong data uploaded. This would be in a user guide but as we currently don't have one it would be nice to document here.
i.e.
```bash
dx run app-eggd_ici_uploader/1.0.0 \
  -irun_folder="<run project ID>:</path/to/output/eggd_tso500>" \
  -iworkflow_id="<workflow ID string>" \
  -iapi_key="<API key file>"
```
would that be suitable?
___
*[`src/script.sh` line 47 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaRxij6oiklLRzbwrB:-OBjfRTe5lra-Xfcex2T:b-mgafwt) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L47)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I don't think so, SNOMED IDs should be specific to samples, but the way we're using them right now is just as a placeholder until something specific is decided on. This won't change across pipelines for the time being.
</blockquote></details>

Fair enough, it will might require other changes anyway so let's leave it for now to get this published at V1.
___
*[`src/script.sh` line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe28n9BnmhfHkJ-b5q:-OBjfn0S1VvMvK42XWvA:b-b1dytz) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L70)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I think this is something we should discuss as a group, since this has implications for the workflow config too
</blockquote></details>

yes let's discuss
___
*[`src/script.sh` line 89 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe3zsE4NkGdO2hhS-f:-OBjfdLe4YnRSJXpE2D_:biof9bl) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L89)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Thanks :) it's a nice feature I forgot to give the user an opportunity to invoke because there's no user argument for it haha. If I add it I'll need to repeat all the testing... will decide if it's something I want to do
</blockquote></details>

Did you decide on this? I think as we have made quite a few changes we should repeat testing with the final version anyway.
___
*[`src/script.sh` line 20 at r3](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBjf22x7C1sOShwHrSJ:-OBjf22x7C1sOShwHrSK:bs4f8m5) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/e5bff269349dd364f62e94468863ce8bb62cdc04/src/script.sh#L20)):*
> ```Shell
>         dx download -r "${RUN_PATH}" -o "${OUT_FOLDER}"
>     else
>         dx download -r "${DX_PROJECT_CONTEXT_ID}":"${RUN_PATH}" -o "${OUT_FOLDER}"
> ```

I think this should be "${DX_PROJECT_CONTEXT_ID}:${RUN_PATH}"


<!-- Sent from Reviewable.io -->

2024-11-15 12:09 UTC, PolarisAstrum-NHS approved these changes
> Reviewed 1 of 8 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4)* status: all files reviewed, 4 unresolved discussions (waiting on @RSWilson1 and @spaul91)

___
*[`README.md` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPgC87eB9LLeMlGBY:-OBjfOsTDEDOtF9C8Q3D:b-w6pf9b) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L32)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Isn't it enough as it is? The section tells you to get the workflow ID from ICI, and I don't think it should be the responsibility of these docs to outline all of the steps needed to define and copy a workflow ID from ICI.

I'm afraid I don't quite understand what you need from me on this, so if you know what to replace this with, please feel free to make the edits and open a PR against the dev branch.
</blockquote></details>

I agree Sophie, getting the workflow ID seems like something that belongs in a confluence page rather than the readme file.
___
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBjgmQR8NDqpvZaYWNk:b-d5qd13) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I'm sorry, but I respectfully disagree. It's a feature of DNANexus, and anyone using this app should be familiar with the way paths are specified. I think it's fine as it is, and I don't see what's ambiguous about the placeholders I'm using already
</blockquote></details>

If we're going to use this for tso500, I think it makes sense to give an example of the output path (<project-id>:tso500/output/). It might seem obvious now, but I'm thinking 6 months or a year down the line when it's not as familiar to us, or people other than us are using the app
___
*[`src/script.sh` line 47 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaRxij6oiklLRzbwrB:-OBjhg5t8TGGH07aGi_0:bvcwkuz) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L47)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I don't think so, SNOMED IDs should be specific to samples, but the way we're using them right now is just as a placeholder until something specific is decided on. This won't change across pipelines for the time being.
</blockquote></details>

For now we're just using this for TSO500. If this does turn out to be a problem later for MYE, making the SNOMED IDs configurable could be added as a feature in a later version


<!-- Sent from Reviewable.io -->

2024-11-15 13:28 UTC, RSWilson1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4)* status: all files reviewed, 3 unresolved discussions (waiting on @PolarisAstrum-NHS and @spaul91)

___
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBk-0s7Bwbq6UVh7Fug:b-3jtivy) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

If we're going to use this for tso500, I think it makes sense to give an example of the output path (<project-id>:tso500/output/). It might seem obvious now, but I'm thinking 6 months or a year down the line when it's not as familiar to us, or people other than us are using the app
</blockquote></details>

Yes and we should probably have this as a separate example for TSO500 as we might use this for MYE in the future.


<!-- Sent from Reviewable.io -->

2024-11-15 13:43 UTC, spaul91 commented
*[`src/script.sh` line 20 at r3](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBjf22x7C1sOShwHrSJ:-OBk2zDvCzYf-PThkDcy:b-qadj4q) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/e5bff269349dd364f62e94468863ce8bb62cdc04/src/script.sh#L20)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

I think this should be "${DX_PROJECT_CONTEXT_ID}:${RUN_PATH}"
</blockquote></details>

there must have been a reason I did this in this horrid, wacky way. Maybe ShellCheck threw a warning at me. I'll check


<!-- Sent from Reviewable.io -->

2024-11-15 13:46 UTC, spaul91 commented
*[`README.md` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPgC87eB9LLeMlGBY:-OBk38sZ8w5ivLU2R5Lp:bmnadu2) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L32)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

I agree Sophie, getting the workflow ID seems like something that belongs in a confluence page rather than the readme file.
</blockquote></details>

@RSWilson1 I think that's kind of confusing, it doesn't tell you where to look for the workflow ID (which is the important part, not all of the things it encapsulates). I'd suggest leaving it as it is imo, but again if you can think of a more concise and clear way to word it, I'd be more than happy to replace what's there now


<!-- Sent from Reviewable.io -->

2024-11-15 13:50 UTC, spaul91 commented
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBk3p_mCBFXJ568h7xV:b-j7xu0m) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Yes and we should probably have this as a separate example for TSO500 as we might use this for MYE in the future.
</blockquote></details>

Instructions will be in the user guide for running that specific workflow, I don't want to go down the route of adding examples for every pipeline in the app instructions themselves, because they should be general, not specific. As a compromise, would you accept me adding a single path for TSO500 and making it clear that it's an example?


<!-- Sent from Reviewable.io -->

2024-11-15 13:53 UTC, spaul91 commented
*[`src/script.sh` line 89 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe3zsE4NkGdO2hhS-f:-OBk4zXT03c_P1r-ITRU:bd65mjf) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L89)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Did you decide on this? I think as we have made quite a few changes we should repeat testing with the final version anyway.
</blockquote></details>

I'm being dumb. I did add it as a feature in dxapp.json, I just didn't put that in the README. I could go either way on testing the dry-run feature, it's only really for local testing. I'll be repeating testing either way since as you said we've changed a lot about this app at this point.


<!-- Sent from Reviewable.io -->

2024-11-15 13:58 UTC, spaul91 commented
*[`src/script.sh` line 20 at r3](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBjf22x7C1sOShwHrSJ:-OBk6R3V8ht2Oy78VabV:bw7ebb4) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/e5bff269349dd364f62e94468863ce8bb62cdc04/src/script.sh#L20)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

there must have been a reason I did this in this horrid, wacky way. Maybe ShellCheck threw a warning at me. I'll check
</blockquote></details>

Nope, just me being silly. Thanks for catching this one


<!-- Sent from Reviewable.io -->

2024-11-15 14:10 UTC, RSWilson1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @PolarisAstrum-NHS and @spaul91)

___
*[`README.md` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaPgC87eB9LLeMlGBY:-OBk99HQ5p7AUycG968o:b67wm6q) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L32)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

@RSWilson1 I think that's kind of confusing, it doesn't tell you where to look for the workflow ID (which is the important part, not all of the things it encapsulates). I'd suggest leaving it as it is imo, but again if you can think of a more concise and clear way to word it, I'd be more than happy to replace what's there now
</blockquote></details>

Fair enough, as long as it's documented in the user manual that should be sufficient
___
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBk8mlt4wozkcAMNEo4:b-4b3qgg) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Instructions will be in the user guide for running that specific workflow, I don't want to go down the route of adding examples for every pipeline in the app instructions themselves, because they should be general, not specific. As a compromise, would you accept me adding a single path for TSO500 and making it clear that it's an example?
</blockquote></details>

I have found it helpful in the past to have some examples which just help make it clear how to use this of course we don't need an example for every assay or use-case. Yes let's add a single path for TSO500 as an example that way it's recorded somewhere :thumbsup: 
___
*[`src/script.sh` line 89 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe3zsE4NkGdO2hhS-f:-OBk8e21Ammcj15UkJL8:b-q74txj) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L89)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I'm being dumb. I did add it as a feature in dxapp.json, I just didn't put that in the README. I could go either way on testing the dry-run feature, it's only really for local testing. I'll be repeating testing either way since as you said we've changed a lot about this app at this point.
</blockquote></details>

great!


<!-- Sent from Reviewable.io -->

2024-11-15 14:25 UTC, PolarisAstrum-NHS approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4)* status: all files reviewed, 2 unresolved discussions (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2024-11-15 15:54 UTC, spaul91 commented
*[`src/script.sh` line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBe28n9BnmhfHkJ-b5q:-OBkX5_F6dD2Vbmv-_j3:b-i5bnm9) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/src/script.sh#L70)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

yes let's discuss
</blockquote></details>

Done - Discussed offline, non-issue


<!-- Sent from Reviewable.io -->

2024-11-15 15:58 UTC, spaul91 commented
*[`README.md` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4#-OBaQ_i-2sm1zEdHMhR-:-OBkXuNEBGtyxzeCxKdP:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/51dfb0320b10af187ab4e693e76257a1c1caf8cc/README.md#L35)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

I have found it helpful in the past to have some examples which just help make it clear how to use this of course we don't need an example for every assay or use-case. Yes let's add a single path for TSO500 as an example that way it's recorded somewhere :thumbsup:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-15 16:01 UTC, RSWilson1 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2024-11-15 16:02 UTC, merged